---
# This playbook install the basic files required in a server
- name: copy ES and its apps 
  tags:
   - install
  unarchive: src=opt/splunk/etc/apps.tar.gz dest=/opt/splunk/etc/ owner=root group=root mode=755

- name: install es_demo app 
  tags:
   - install
   - es_demo_app
  copy: src=opt/splunk/etc/apps/es_demo dest=/opt/splunk/etc/apps owner=root group=root mode=755


- name: copy passwd file to root dir - needed by es_demo_reset.sh cron 
  tags:
   - install
  copy: src=splunk_creds/passwd dest=/root/ owner=root group=root mode=700

- name: copy cron.d to reset demo nigthly 
  tags:
   - install
  copy: src=etc/cron.d/es_demo_reset.sh dest=/etc/cron.d/es_demo_reset.sh owner=root group=root mode=700

- name: run reset script for the first time
  tags:
   - install
  shell: /etc/cron.d/es_demo_reset.sh
